Repository nccgroup/ScoutSuite, pull requests merged in 2020-12, with the labels that each got.

#917 release/5.10.2
  ScoutSuite/__init__.py
  ScoutSuite/data/aws/ip-ranges/aws.json
  ScoutSuite/output/data/html/partials/aws/services.acm.regions.id.certificates.html
  ScoutSuite/output/data/html/partials/aws/services.cloudtrail.regions.id.trails.html
  ScoutSuite/output/data/html/partials/aws/services.config.regions.id.recorders.html
  ScoutSuite/output/data/html/partials/aws/services.ec2.regions.id.snapshots.html
  ScoutSuite/output/data/html/partials/aws/services.ec2.regions.id.vpcs.id.instances.html
  ScoutSuite/output/data/html/partials/aws/services.iam.credential_reports.html
  ScoutSuite/output/data/html/partials/aws/services.iam.groups.html
  ScoutSuite/output/data/html/partials/aws/services.iam.users.html
  ScoutSuite/output/data/html/partials/aws/services.rds.regions.id.vpcs.id.instances.html
  ScoutSuite/providers/aws/facade/ec2.py
  ScoutSuite/providers/aws/facade/s3.py
  ScoutSuite/providers/aws/provider.py
  ScoutSuite/providers/aws/resources/acm/certificates.py
  ScoutSuite/providers/aws/resources/cloudtrail/trails.py
  ScoutSuite/providers/aws/resources/ec2/instances.py
  ScoutSuite/providers/aws/resources/ec2/snapshots.py
  ScoutSuite/providers/aws/resources/ec2/volumes.py
  ScoutSuite/providers/aws/resources/iam/credentialreports.py
  ScoutSuite/providers/aws/rules/findings/cloudtrail-no-encryption-with-kms.json
  ScoutSuite/providers/aws/rules/findings/ec2-ebs-snapshot-not-encrypted.json
  ScoutSuite/providers/aws/rules/findings/ec2-ebs-snapshot-public.json
  ScoutSuite/providers/aws/rules/findings/iam-managed-policy-allows-NotActions.json
  ScoutSuite/providers/aws/rules/findings/iam-managed-policy-allows-full-privileges.json
  ScoutSuite/providers/aws/rules/findings/iam-managed-policy-allows-non-sts-action.json
  ScoutSuite/providers/aws/rules/findings/iam-managed-policy-for-role.json
  ScoutSuite/providers/aws/rules/findings/iam-unused-credentials-not-disabled.json
  ScoutSuite/providers/aws/rules/findings/kms-cmk-rotation-disabled.json
  ScoutSuite/providers/aws/rules/findings/route53-domain-transferlock-not-authorized.json
  ScoutSuite/providers/azure/rules/findings/appservice-outdated-http-version.json
  ScoutSuite/providers/azure/rules/findings/appservice-tls-v1-supported.json
  ScoutSuite/providers/azure/rules/rulesets/cis-1.1.0.json
  ScoutSuite/providers/azure/rules/rulesets/default.json
  ScoutSuite/providers/gcp/facade/base.py
  ScoutSuite/providers/gcp/resources/gce/instances.py
  docker/Dockerfile
  docker/build.sh
  docker/config/build.env
  docker/docker-compose.yaml
  requirements.txt
Labels: release

#937 Fix Client DOM XSS
  ScoutSuite/output/data/inc-scoutsuite/scoutsuite.js
Labels: bugfix

#945 GCP: Always check IAM policies
  ScoutSuite/providers/gcp/facade/base.py
Labels: component-provider-gcp, enhancement
