Repository nccgroup/ScoutSuite, pull requests merged in 2021-02, with the labels that each got.

#980 Added new mock API for development purpose
  ScoutSuite/frontend/src/App.js
  ScoutSuite/frontend/src/api/api.js
  ScoutSuite/frontend/src/api/cache.js
  ScoutSuite/frontend/src/api/temp/scoutsuite_results_aws.json
  ScoutSuite/frontend/src/api/useAPI.js
  ScoutSuite/frontend/src/pages/useAPIExample/index.js
Labels: polymtl, refactoring

#1023 Ignore profiling output
  .gitignore
Labels: enhancement

#1022 Add missing ARNs for AWS resources
  ScoutSuite/output/data/html/partials/accordion_policy.html
  ScoutSuite/output/data/html/partials/aws/services.cloudwatch.regions.id.metric_filters.html
  ScoutSuite/output/data/html/partials/aws/services.elb.regions.id.elb_policies.html
  ScoutSuite/output/data/html/partials/aws/services.emr.regions.id.vpcs.id.clusters.html
  ScoutSuite/output/data/html/partials/aws/services.kms.regions.id.keys.html
  ScoutSuite/output/data/html/partials/aws/services.redshift.regions.id.parameter_groups.html
  ScoutSuite/output/data/html/partials/aws/services.route53.regions.id.hosted_zones.html
  ScoutSuite/output/data/html/partials/aws/services.ses.regions.id.identities.html
  ScoutSuite/output/data/html/partials/aws/services.sns.regions.id.topics.html
  ScoutSuite/output/data/html/partials/aws/services.vpc.regions.id.flow_logs.html
  ScoutSuite/output/data/html/partials/aws/services.vpc.regions.id.peering_connections.html
  ScoutSuite/output/data/html/partials/aws/services.vpc.regions.id.vpcs.id.network_acls.html
  ScoutSuite/output/data/html/partials/aws/services.vpc.regions.id.vpcs.id.subnets.html
  ScoutSuite/output/data/inc-scoutsuite/helpers.js
  ScoutSuite/providers/aws/provider.py
  ScoutSuite/providers/aws/resources/cloudwatch/metric_filters.py
  ScoutSuite/providers/aws/resources/directconnect/connections.py
  ScoutSuite/providers/aws/resources/ec2/ami.py
  ScoutSuite/providers/aws/resources/ec2/instances.py
  ScoutSuite/providers/aws/resources/ec2/networkinterfaces.py
  ScoutSuite/providers/aws/resources/ec2/securitygroups.py
  ScoutSuite/providers/aws/resources/ec2/snapshots.py
  ScoutSuite/providers/aws/resources/ec2/volumes.py
  ScoutSuite/providers/aws/resources/efs/filesystems.py
  ScoutSuite/providers/aws/resources/elasticache/cluster.py
  ScoutSuite/providers/aws/resources/elb/load_balancers.py
  ScoutSuite/providers/aws/resources/elb/policies.py
  ScoutSuite/providers/aws/resources/emr/clusters.py
  ScoutSuite/providers/aws/resources/kms/grants.py
  ScoutSuite/providers/aws/resources/rds/subnetgroups.py
  ScoutSuite/providers/aws/resources/redshift/cluster_parameter_groups.py
  ScoutSuite/providers/aws/resources/redshift/cluster_parameters.py
  ScoutSuite/providers/aws/resources/redshift/clusters.py
  ScoutSuite/providers/aws/resources/route53/domains.py
  ScoutSuite/providers/aws/resources/route53/hosted_zones.py
  ScoutSuite/providers/aws/resources/s3/buckets.py
  ScoutSuite/providers/aws/resources/ses/identities.py
  ScoutSuite/providers/aws/resources/ses/identity_policies.py
  ScoutSuite/providers/aws/resources/sns/subscriptions.py
  ScoutSuite/providers/aws/resources/vpc/flow_logs.py
  ScoutSuite/providers/aws/resources/vpc/network_acls.py
  ScoutSuite/providers/aws/resources/vpc/peering_connections.py
  ScoutSuite/providers/aws/resources/vpc/subnets.py
  ScoutSuite/providers/aws/resources/vpcs.py
  ScoutSuite/providers/aws/utils.py
Labels: component-provider-aws, enhancement

#1024 Correct matching for EC2 instances in VPCs partial
  ScoutSuite/output/data/html/partials/aws/services.vpc.regions.id.vpcs.html
  ScoutSuite/providers/aws/metadata.json
  ScoutSuite/providers/aws/provider.py
Labels: bug, component-UI, component-provider-aws

#1090 Feature/1088 update useapi
  ScoutSuite/frontend/package-lock.json
  ScoutSuite/frontend/package.json
  ScoutSuite/frontend/src/api/api.js
  ScoutSuite/frontend/src/api/paths.js
  ScoutSuite/frontend/src/api/useAPI.js
  ScoutSuite/frontend/src/components/Breadcrumb/Findings/index.js
  ScoutSuite/frontend/src/components/Breadcrumb/Provider/index.js
  ScoutSuite/frontend/src/components/Partial/PartialSection/index.js
  ScoutSuite/frontend/src/components/Partial/PartialValue/index.js
  ScoutSuite/frontend/src/components/Partial/Wrapper/index.js
  ScoutSuite/frontend/src/components/Partial/context.js
  ScoutSuite/frontend/src/components/Partial/index.js
  ScoutSuite/frontend/src/components/ServiceCard/index.js
  ScoutSuite/frontend/src/components/Table/Renderer/index.js
  ScoutSuite/frontend/src/components/Table/index.js
  ScoutSuite/frontend/src/components/Table/style.scss
  ScoutSuite/frontend/src/layout/Header/style.scss
  ScoutSuite/frontend/src/layout/Menu/MenuElement/index.js
  ScoutSuite/frontend/src/layout/Menu/MenuGroup/index.js
  ScoutSuite/frontend/src/layout/Menu/SubMenu/index.js
  ScoutSuite/frontend/src/layout/Menu/style.scss
  ScoutSuite/frontend/src/layout/index.js
  ScoutSuite/frontend/src/pages/Dashboard/TabsContent/Summary/index.js
  ScoutSuite/frontend/src/pages/Dashboard/index.js
  ScoutSuite/frontend/src/pages/Findings/formatters/Description/index.js
  ScoutSuite/frontend/src/pages/Findings/formatters/Description/style.scss
  ScoutSuite/frontend/src/pages/Findings/formatters/Name/index.js
  ScoutSuite/frontend/src/pages/Findings/index.js
  ScoutSuite/frontend/src/pages/Findings/style.scss
  ScoutSuite/frontend/src/pages/FlaggedItems/SelectedItemContainer/index.js
  ScoutSuite/frontend/src/pages/FlaggedItems/formatters/Name/index.js
  ScoutSuite/frontend/src/pages/FlaggedItems/index.js
  ScoutSuite/frontend/src/partials/Default/Informations/index.js
  ScoutSuite/frontend/src/partials/Default/Informations/style.scss
  ScoutSuite/frontend/src/partials/Default/index.js
  ScoutSuite/frontend/src/partials/S3/BucketInformations/index.js
  ScoutSuite/frontend/src/partials/aws/s3.buckets.id/BucketInformations/index.js
  ScoutSuite/frontend/src/partials/aws/s3.buckets.id/BucketInformations/style.scss
  ScoutSuite/frontend/src/partials/aws/s3.buckets.id/BucketPolicies/index.js
  ScoutSuite/frontend/src/partials/aws/s3.buckets.id/BucketPolicies/style.scss
  ScoutSuite/frontend/src/partials/aws/s3.buckets.id/index.js
  ScoutSuite/frontend/src/utils/Dashboard/index.js
Labels: component-UI, polymtl, refactoring

#1027 refactor rules of cis azure storage section to match v1.2.0 documenta…
  ScoutSuite/providers/azure/rules/findings/storageaccount-access-keys-not-rotated.json
  ScoutSuite/providers/azure/rules/findings/storageaccount-account-allowing-clear-text.json
  ScoutSuite/providers/azure/rules/findings/storageaccount-public-blob-container.json
  ScoutSuite/providers/azure/rules/findings/storageaccount-public-traffic-allowed.json
  ScoutSuite/providers/azure/rules/findings/storageaccount-trusted-microsoft-services.json
Labels: cleanup, refactoring
