Repository nccgroup/ScoutSuite, pull requests merged in 2021-04, with the labels that each got.

#1225 Enhancement/gcp sql 6.1.2
  ScoutSuite/output/data/html/partials/gcp/services.cloudsql.projects.id.instances.html
  ScoutSuite/providers/gcp/resources/cloudsql/database_instances.py
  ScoutSuite/providers/gcp/rules/findings/cloudsql-mysql-instances-local-infile-on.json
  ScoutSuite/providers/gcp/rules/rulesets/cis-1.1.0.json
  ScoutSuite/providers/gcp/rules/rulesets/default.json
Labels: polymtl

#1240 Feature/1208 add download buttons
  ScoutSuite/frontend/src/components/DownloadButton/index.js
  ScoutSuite/frontend/src/components/Table/Renderer/index.js
  ScoutSuite/frontend/src/components/Table/index.js
  ScoutSuite/frontend/src/components/Table/style.scss
  ScoutSuite/frontend/src/layout/Menu/style.scss
  ScoutSuite/frontend/src/pages/FindingItems/index.js
  ScoutSuite/frontend/src/pages/Resources/index.js
Labels: component-UI, polymtl, refactoring

#1224 Enhancement/gcp iam 1.9 1.10
  ScoutSuite/output/data/html/partials/gcp/services.kms.projects.id.keyrings.html
  ScoutSuite/providers/gcp/facade/kms.py
  ScoutSuite/providers/gcp/resources/kms/keys.py
  ScoutSuite/providers/gcp/resources/kms/kms_policy.py
  ScoutSuite/providers/gcp/rules/findings/kms-cryptokeys-anonymously-publicly-accessible.json
  ScoutSuite/providers/gcp/rules/findings/kms-encryption-keys-not-rotated.json
  ScoutSuite/providers/gcp/rules/rulesets/cis-1.1.0.json
  ScoutSuite/providers/gcp/rules/rulesets/default.json
Labels: polymtl

#1226 Enhancement/gcp sql 6.3
  ScoutSuite/output/data/html/partials/gcp/services.cloudsql.projects.id.instances.html
  ScoutSuite/providers/gcp/resources/cloudsql/base.py
  ScoutSuite/providers/gcp/resources/cloudsql/database_instances.py
  ScoutSuite/providers/gcp/rules/findings/cloudsql-sqlservers-instances-contained-database-authentication-on.json
  ScoutSuite/providers/gcp/rules/findings/cloudsql-sqlservers-instances-cross-db-ownership-chaining-on.json
  ScoutSuite/providers/gcp/rules/rulesets/cis-1.1.0.json
  ScoutSuite/providers/gcp/rules/rulesets/default.json
Labels: polymtl

#1241 fix a bug in azure security center section
  ScoutSuite/output/data/html/partials/azure/services.securitycenter.subscriptions.id.security_contacts.html
  ScoutSuite/providers/azure/rules/findings/securitycenter-auto-provisioning-off.json
  ScoutSuite/providers/azure/rules/findings/securitycenter-security-contacts-email-not-set.json
  ScoutSuite/providers/azure/rules/findings/securitycenter-security-contacts-no-admin-email-notifications.json
  ScoutSuite/providers/azure/rules/findings/securitycenter-security-contacts-no-email-notifications.json
  ScoutSuite/providers/azure/rules/findings/securitycenter-security-contacts-not-set.json
  ScoutSuite/providers/azure/rules/findings/securitycenter-security-contacts-phone-not-set.json
Labels: polymtl

#1239 refactor iam rules from gcp
  ScoutSuite/providers/gcp/rules/findings/iam-gmail-accounts-used.json
  ScoutSuite/providers/gcp/rules/findings/iam-lack-of-service-account-key-rotation.json
  ScoutSuite/providers/gcp/rules/findings/iam-primitive-role-in-use.json
  ScoutSuite/providers/gcp/rules/findings/iam-sa-has-admin-privileges.json
  ScoutSuite/providers/gcp/rules/findings/iam-service-account-with-user-managed-keys.json
  ScoutSuite/providers/gcp/rules/findings/iam-user-has-sa-user-role.json
Labels: polymtl

#1242 Enhancement/gcp vm
  ScoutSuite/output/data/html/partials/gcp/services.computeengine.projects.id.zones.id.instances.html
  ScoutSuite/providers/gcp/resources/gce/instances.py
  ScoutSuite/providers/gcp/rules/findings/computeengine-instance-block-project-ssh-keys-disabled.json
  ScoutSuite/providers/gcp/rules/findings/computeengine-instance-connecting-serial-ports-enabled.json
  ScoutSuite/providers/gcp/rules/findings/computeengine-instance-default-service-account.json
  ScoutSuite/providers/gcp/rules/findings/computeengine-instance-disk-not-csek-encrypted.json
  ScoutSuite/providers/gcp/rules/findings/computeengine-instance-full-api-access.json
  ScoutSuite/providers/gcp/rules/findings/computeengine-instance-ip-forwarding-enabled.json
  ScoutSuite/providers/gcp/rules/findings/computeengine-instance-os-login-disabled.json
  ScoutSuite/providers/gcp/rules/findings/computeengine-instance-public-ip-adresses.json
  ScoutSuite/providers/gcp/rules/findings/computeengine-instance-shielded-vm-disabled.json
  ScoutSuite/providers/gcp/rules/rulesets/cis-1.1.0.json
  ScoutSuite/providers/gcp/rules/rulesets/default.json
Labels: polymtl

#1238 Enhancement/gcp sql refactor 6.6
  ScoutSuite/providers/gcp/rules/findings/cloudsql-instance-backups-disabled.json
  ScoutSuite/providers/gcp/rules/findings/cloudsql-instance-is-open-to-the-world.json
  ScoutSuite/providers/gcp/rules/findings/cloudsql-instance-ssl-not-required.json
  ScoutSuite/providers/gcp/rules/findings/cloudsql-instances-public-ips.json
  ScoutSuite/providers/gcp/rules/rulesets/cis-1.1.0.json
  ScoutSuite/providers/gcp/rules/rulesets/default.json
Labels: polymtl

#1249 Enhancement/gcp logging 2.4 2.11
  ScoutSuite/output/data/html/partials/gcp/services.stackdriverlogging.projects.id.logging_metrics.html
  ScoutSuite/output/data/html/partials/gcp/services.stackdrivermonitoring.projects.id.monitoring_alert_policies.html
  ScoutSuite/providers/gcp/metadata.json
  ScoutSuite/providers/gcp/resources/stackdriverlogging/base.py
  ScoutSuite/providers/gcp/resources/stackdriverlogging/logging_metrics.py
  ScoutSuite/providers/gcp/resources/stackdrivermonitoring/base.py
  ScoutSuite/providers/gcp/resources/stackdrivermonitoring/monitoring_alert_policies.py
  ScoutSuite/providers/gcp/rules/findings/stackdriverlogging-metric-filter-does-not-exist-audit-config-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdriverlogging-metric-filter-does-not-exist-cloud-storage-iam-permission-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdriverlogging-metric-filter-does-not-exist-custom-role-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdriverlogging-metric-filter-does-not-exist-project-ownership-assignment.json
  ScoutSuite/providers/gcp/rules/findings/stackdriverlogging-metric-filter-does-not-exist-sql-instance-config-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdriverlogging-metric-filter-does-not-exist-vpc-network-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdriverlogging-metric-filter-does-not-exist-vpc-network-firewall-rule-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdriverlogging-metric-filter-does-not-exist-vpc-network-route-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdrivermonitoring-alerts-does-not-exist-audit-config-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdrivermonitoring-alerts-does-not-exist-cloud-storage-iam-permission-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdrivermonitoring-alerts-does-not-exist-custom-role-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdrivermonitoring-alerts-does-not-exist-project-ownership-assignment.json
  ScoutSuite/providers/gcp/rules/findings/stackdrivermonitoring-alerts-does-not-exist-sql-instance-config-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdrivermonitoring-alerts-does-not-exist-vpc-network-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdrivermonitoring-alerts-does-not-exist-vpc-network-firewall-rule-changes.json
  ScoutSuite/providers/gcp/rules/findings/stackdrivermonitoring-alerts-does-not-exist-vpc-network-route-changes.json
  ScoutSuite/providers/gcp/rules/rulesets/cis-1.1.0.json
  ScoutSuite/providers/gcp/rules/rulesets/default.json
Labels: polymtl

#1237 Enhancement/gcp sql 6.2
  ScoutSuite/output/data/html/partials/gcp/services.cloudsql.projects.id.instances.html
  ScoutSuite/providers/gcp/resources/cloudsql/database_instances.py
  ScoutSuite/providers/gcp/rules/findings/cloudsql-postgresql-instances-log-checkpoints-off.json
  ScoutSuite/providers/gcp/rules/findings/cloudsql-postgresql-instances-log-connections-off.json
  ScoutSuite/providers/gcp/rules/findings/cloudsql-postgresql-instances-log-disconnections-off.json
  ScoutSuite/providers/gcp/rules/findings/cloudsql-postgresql-instances-log-lock-waits-off.json
  ScoutSuite/providers/gcp/rules/findings/cloudsql-postgresql-instances-log-min-duration-not-set-1.json
  ScoutSuite/providers/gcp/rules/findings/cloudsql-postgresql-instances-log-min-messages-not-set.json
  ScoutSuite/providers/gcp/rules/findings/cloudsql-postgresql-instances-log-temp-files-not-set-0.json
  ScoutSuite/providers/gcp/rules/rulesets/cis-1.1.0.json
  ScoutSuite/providers/gcp/rules/rulesets/default.json
Labels: polymtl

#1255 Fixed updating the main menu
  ScoutSuite/frontend/src/layout/Menu/MenuElement/index.js
  ScoutSuite/frontend/src/layout/index.js
Labels: bugfix, polymtl

#1256 Fixed table not going back to page 1
  ScoutSuite/frontend/src/components/Table/Renderer/index.js
Labels: bugfix, polymtl

#1261 Merge server exceptions with local exceptions
  ScoutSuite/frontend/src/components/Exceptions/DownloadButton/index.js
Labels: component-UI, polymtl, refactoring

#1267 fix rule 6.6 from gcp cis
  ScoutSuite/providers/gcp/rules/findings/cloudsql-instances-public-ips.json
Labels: polymtl

#1251 Enhancement/gcp fix errors
  ScoutSuite/providers/gcp/resources/kms/keys.py
  ScoutSuite/providers/gcp/rules/findings/kms-encryption-keys-not-rotated.json
Labels: polymtl

#1259 Feature/1257 network interfaces subnets
  ScoutSuite/frontend/src/partials/azure/keyvault.subscriptions.id.vaults.id/index.js
  ScoutSuite/frontend/src/partials/azure/network.subscriptions.id.application_security_groups.id/index.js
  ScoutSuite/frontend/src/partials/azure/network.subscriptions.id.network_interfaces.id/index.js
  ScoutSuite/frontend/src/partials/azure/network.subscriptions.id.security_groups.id/index.js
  ScoutSuite/frontend/src/partials/azure/network.subscriptions.id.virtual_networks.id/Subnets/index.js
  ScoutSuite/frontend/src/partials/azure/network.subscriptions.id.virtual_networks.id/index.js
  ScoutSuite/frontend/src/partials/azure/virtualmachines.subscriptions.id.instances.id/index.js
Labels: component-UI, polymtl, refactoring

#1273 Fixed finding descriptions
  ScoutSuite/frontend/src/pages/Findings/formatters/Description/index.js
  ScoutSuite/frontend/src/pages/Findings/formatters/Description/style.scss
  ScoutSuite/frontend/src/pages/Findings/index.js
Labels: component-UI, polymtl, refactoring

#1263 Feature/1206 loading page and errors
  ScoutSuite/frontend/public/index.html
  ScoutSuite/frontend/public/logo.png
  ScoutSuite/frontend/public/logo192.png
  ScoutSuite/frontend/public/logo512.png
  ScoutSuite/frontend/src/App.js
  ScoutSuite/frontend/src/api/api.js
  ScoutSuite/frontend/src/api/temp/items.json
  ScoutSuite/frontend/src/api/temp/scoutsuite_results_aws.json
  ScoutSuite/frontend/src/components/AppLoader/index.js
  ScoutSuite/frontend/src/components/AppLoader/style.scss
  ScoutSuite/frontend/src/components/Breadcrumb/index.js
  ScoutSuite/frontend/src/components/ErrorBoundary/index.js
  ScoutSuite/frontend/src/layout/Header/index.js
  ScoutSuite/frontend/src/layout/Header/style.scss
  ScoutSuite/frontend/src/pages/404/index.js
  ScoutSuite/frontend/src/pages/404/style.scss
  ScoutSuite/frontend/src/pages/Dashboard/index.js
  ScoutSuite/frontend/src/pages/FindingItems/SelectedItemContainer/index.js
  ScoutSuite/frontend/src/pages/FindingItems/index.js
  ScoutSuite/frontend/src/pages/Resources/ResourcePartialWrapper/index.js
  ScoutSuite/frontend/src/pages/Resources/index.js
Labels: component-UI, polymtl, refactoring

#1274 Add dummy workflow
  .github/workflows/frontend-build.yml
Labels: polymtl, refactoring

#1276 Update Partials for GCP CISv1.1.0 on React Frontend
  ScoutSuite/frontend/package-lock.json
  ScoutSuite/frontend/package.json
  ScoutSuite/frontend/src/partials/gcp/cloudsql.projects.id.instances.id/index.js
  ScoutSuite/frontend/src/partials/gcp/computeengine.projects.id.networks.id/index.js
  ScoutSuite/frontend/src/partials/gcp/computeengine.projects.id.zones.id.instances.id/index.js
  ScoutSuite/frontend/src/partials/gcp/dns.projects.id.managed_zones.id/index.js
  ScoutSuite/frontend/src/partials/gcp/iam.projects.id.bindings_seperation_duties.id/index.js
  ScoutSuite/frontend/src/partials/gcp/kms.projects.id.keyrings.id/index.js
  ScoutSuite/frontend/src/partials/gcp/stackdriverlogging.projects.id.logging_metrics.id/index.js
  ScoutSuite/frontend/src/partials/gcp/stackdrivermonitoring.projects.id.monitoring_alert_policies.id/index.js
  ScoutSuite/output/data/html/partials/gcp/services.dns.projects.id.managed_zones.html
  ScoutSuite/providers/gcp/resources/stackdriverlogging/logging_metrics.py
  ScoutSuite/providers/gcp/resources/stackdrivermonitoring/monitoring_alert_policies.py
Labels: polymtl

#1252 fix and add missing ids in aws resources
  ScoutSuite/providers/aws/facade/iam.py
  ScoutSuite/providers/aws/resources/awslambda/functions.py
  ScoutSuite/providers/aws/resources/cloudformation/stacks.py
  ScoutSuite/providers/aws/resources/cloudfront/distributions.py
  ScoutSuite/providers/aws/resources/cloudtrail/trails.py
  ScoutSuite/providers/aws/resources/cloudwatch/alarms.py
  ScoutSuite/providers/aws/resources/config/recorders.py
  ScoutSuite/providers/aws/resources/config/rules.py
  ScoutSuite/providers/aws/resources/ec2/networkinterfaces.py
  ScoutSuite/providers/aws/resources/efs/filesystems.py
  ScoutSuite/providers/aws/resources/elasticache/cluster.py
  ScoutSuite/providers/aws/resources/elasticache/parametergroups.py
  ScoutSuite/providers/aws/resources/elasticache/securitygroups.py
  ScoutSuite/providers/aws/resources/elasticache/subnetgroups.py
  ScoutSuite/providers/aws/resources/elb/load_balancers.py
  ScoutSuite/providers/aws/resources/elb/policies.py
  ScoutSuite/providers/aws/resources/rds/instances.py
  ScoutSuite/providers/aws/resources/rds/parametergroups.py
  ScoutSuite/providers/aws/resources/rds/securitygroups.py
  ScoutSuite/providers/aws/resources/rds/subnetgroups.py
  ScoutSuite/providers/aws/resources/redshift/cluster_security_groups.py
  ScoutSuite/providers/aws/resources/route53/hosted_zones.py
  ScoutSuite/providers/aws/resources/ses/identities.py
  ScoutSuite/providers/aws/resources/sns/topics.py
  ScoutSuite/providers/aws/resources/sqs/queues.py
  ScoutSuite/providers/aws/resources/vpc/flow_logs.py
  ScoutSuite/providers/aws/resources/vpc/peering_connections.py
Labels: polymtl

#1284 Added search for tables
  ScoutSuite/core/server.py
  ScoutSuite/frontend/src/api/paths.js
  ScoutSuite/frontend/src/api/useAPI.js
  ScoutSuite/frontend/src/components/DownloadButton/index.js
  ScoutSuite/frontend/src/components/Table/Filter/index.js
  ScoutSuite/frontend/src/components/Table/Renderer/index.js
  ScoutSuite/frontend/src/components/Table/style.scss
  ScoutSuite/frontend/src/pages/FindingItems/index.js
  ScoutSuite/frontend/src/pages/Resources/index.js
Labels: polymtl, refactoring

#1288 All Azure + GCP partials reviewed
  ScoutSuite/frontend/src/components/ResourceName/index.js
  ScoutSuite/frontend/src/components/Table/Renderer/index.js
  ScoutSuite/frontend/src/components/Table/style.scss
  ScoutSuite/frontend/src/layout/index.js
  ScoutSuite/frontend/src/layout/style.scss
  ScoutSuite/frontend/src/pages/FindingItems/formatters/Name/index.js
  ScoutSuite/frontend/src/pages/Findings/index.js
  ScoutSuite/frontend/src/pages/Findings/style.scss
  ScoutSuite/frontend/src/partials/azure/aad.applications.id/index.js
  ScoutSuite/frontend/src/partials/azure/appservice.subscriptions.id.web_apps.id/index.js
  ScoutSuite/frontend/src/partials/azure/network.subscriptions.id.security_groups.id/index.js
  ScoutSuite/frontend/src/partials/azure/securitycenter.subscriptions.id.pricings.id/index.js
  ScoutSuite/frontend/src/partials/azure/storageaccounts.subscriptions.id.storage_accounts.id/index.js
  ScoutSuite/frontend/src/partials/azure/virtualmachines.subscriptions.id.instances.id/index.js
  ScoutSuite/frontend/src/partials/gcp/cloudsql.projects.id.instances.id/index.js
  ScoutSuite/frontend/src/partials/gcp/cloudstorage.projects.id.buckets.id/index.js
  ScoutSuite/frontend/src/partials/gcp/computeengine.projects.id.zones.id.instances.id/index.js
  ScoutSuite/frontend/src/partials/gcp/iam.projects.id.bindings.id/index.js
  ScoutSuite/frontend/src/partials/gcp/iam.projects.id.users.id/index.js
  ScoutSuite/frontend/src/variables.scss
Labels: component-UI, polymtl, refactoring

#1289 add missing ids
  ScoutSuite/providers/gcp/resources/stackdriverlogging/metrics.py
  ScoutSuite/providers/gcp/resources/stackdriverlogging/sinks.py
Labels: polymtl

#1286 Feature/fixes based on comments
  ScoutSuite/frontend/package-lock.json
  ScoutSuite/frontend/package.json
  ScoutSuite/frontend/src/components/Exceptions/DownloadButton/index.js
  ScoutSuite/frontend/src/components/Modal/index.js
  ScoutSuite/frontend/src/components/Modal/style.scss
  ScoutSuite/frontend/src/components/ServiceCard/index.js
  ScoutSuite/frontend/src/layout/Header/style.scss
  ScoutSuite/frontend/src/layout/index.js
  ScoutSuite/frontend/src/layout/style.scss
  ScoutSuite/frontend/src/pages/Dashboard/TabsContent/ResourcesDetails/index.js
  ScoutSuite/frontend/src/pages/Dashboard/TabsContent/ResourcesDetails/style.scss
  ScoutSuite/frontend/src/pages/Dashboard/TabsContent/Summary/index.js
  ScoutSuite/frontend/src/pages/Dashboard/TabsContent/Summary/style.scss
  ScoutSuite/frontend/src/pages/Findings/formatters/Description/index.js
  ScoutSuite/frontend/src/pages/Findings/formatters/Description/style.scss
  ScoutSuite/frontend/src/pages/Findings/index.js
  ScoutSuite/frontend/src/utils/Dashboard/index.js
  ScoutSuite/frontend/src/utils/Export/index.js
  ScoutSuite/frontend/src/variables.scss
Labels: component-UI, polymtl, refactoring

#1292 Fixed table rendering issues
  ScoutSuite/frontend/src/components/Table/Renderer/index.js
  ScoutSuite/frontend/src/components/Table/style.scss
  ScoutSuite/frontend/src/pages/Findings/index.js
  ScoutSuite/frontend/src/pages/Resources/index.js
Labels: polymtl

#1293 Bug/fixes before demo
  ScoutSuite/frontend/src/App.js
  ScoutSuite/frontend/src/components/Breadcrumb/PasswordPolicy/index.js
  ScoutSuite/frontend/src/components/Breadcrumb/Permissions/index.js
  ScoutSuite/frontend/src/components/Breadcrumb/index.js
  ScoutSuite/frontend/src/components/DownloadButton/index.js
  ScoutSuite/frontend/src/pages/FindingItems/formatters/Name/index.js
  ScoutSuite/frontend/src/pages/FindingItems/index.js
  ScoutSuite/frontend/src/pages/PasswordPolicyFinding/index.js
  ScoutSuite/frontend/src/pages/Permissions/PermissionsList/formatters/Name/index.js
  ScoutSuite/frontend/src/pages/Resources/formatters/Name/index.js
Labels: polymtl

#1299 Fixed issues noticed by Xavier
  ScoutSuite/frontend/src/partials/azure/network.subscriptions.id.security_groups.id/index.js
  ScoutSuite/frontend/src/partials/azure/network.subscriptions.id.security_groups.id/style.scss
  ScoutSuite/frontend/src/partials/azure/storageaccounts.subscriptions.id.storage_accounts.id/index.js
  ScoutSuite/frontend/src/partials/gcp/cloudstorage.projects.id.buckets.id/index.js
  ScoutSuite/frontend/src/partials/gcp/kubernetesengine.projects.id.zones.id.clusters.id/index.js
Labels: component-UI, polymtl, refactoring
